name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the action daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: morteza363831  # Your GitHub username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
