name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 */24 * * *"  # Run every 24 hours
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - master  # Run on pushes to master branch

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: morteza363831  # Your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          color_snake: orange  # Set the snake color to orange
          color_dots: "#00ff00,#00cc00,#009900,#006600,#003300"  # Gradient of greens for contributions
          # Customize the shape of the contribution grid to form the name "morteza"
          contribution_shape: "morteza"  # This option may not exist; see notes below

      - name: Push GitHub Contribution Grid Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
